name: Split Learning
server:
  num-round: 1
  cut_layers:
    - 10
    - 20
  clients:
    - 1
    - 1
    - 1
  model: VGG16
  parameters:
    load: False
    save: False
  validation: False
  data-mode: uneven
  data-distribution:
    num-data-range:
      - 0
      - 500
    non-iid-rate: 0.5
    refresh-each-round: True
  random-seed: 1

rabbit:
  address: 192.168.101.234
  username: dai
  password: dai

log_path: .

learning:
  learning-rate: 0.01
  momentum: 0.5
  batch-size: 128
  control-count: 3
