name: Split Learning
server:
  local-round: 1
  global-round: 1
  cut_layers:
    - 24
  clients:
    - 4
    - 2
  model: VGG16
  parameters:
    load: False
    save: False
  validation: False
  data-mode: uneven
  data-distribution:
    num-data-range:
      - 0
      - 500
    non-iid-rate: 0.5
    refresh-each-round: True
  random-seed: 1
  client-cluster:
    enable: True
    cluster: AffinityPropagation
    AffinityPropagation:
      damping: 0.9
      max_iter: 1000

rabbit:
  address: 192.168.101.91
  username: dai
  password: dai

log_path: .

learning:
  learning-rate: 0.01
  momentum: 0.5
  batch-size: 128
  control-count: 3
