name: Split Learning
server:
  local-round: 1
  global-round: 1
  clients:
    - 1
    - 1
  no-cluster:
    cut-layers: [7]
  cluster:
    num-cluster: 1
    cut-layers:
      - [7]
    infor-cluster:
      - [1,1]
  model: VGG16
  parameters:
    load: True
    save: True
  validation: True
  data-distribution:
    non-iid: True
    num-sample: 5000
    num-label: 10
    dirichlet:
      alpha: 1
    refresh-each-round: True
  random-seed: 1
  client-cluster:
    enable: False
    auto-partition: False
    syn-cut-layers: False
    special: False
    cluster: AffinityPropagation
    AffinityPropagation:
      damping: 0.9
      max_iter: 1000

rabbit:
  address: 192.168.101.234
  username: dai
  password: dai
  virtual-host: /

log_path: .
debug_mode: True

learning:
  learning-rate: 0.01
  momentum: 0.5
  batch-size: 32
  control-count: 3
  compute-loss:
    mode: normal # normal /FedProx /ReBaFL
    FedProx:
      mu: 0.01
    ReBaFL:
      mu: 0.01
      lambda_aug: 0.1
