name: Split Learning
server:
  local-round: 1
  global-round: 1
  clients:
    - 1
    - 1
  no-cluster:
    cut-layers: [7]
  cluster:
    num-cluster: 1
    cut-layers:
      - [7]
    infor-cluster:
      - [1,1]
  model: VGG16
  parameters:
    load: False
    save: False
  validation: False
  data-distribution:
    num-label: 10
    num-data-range:
      - 250
      - 250
    non-iid-rate: 1
    refresh-each-round: True
  random-seed: 1
  client-cluster:
    enable: False
    auto-partition: False
    syn-cut-layers: False
    special: False
    cluster: AffinityPropagation
    AffinityPropagation:
      damping: 0.9
      max_iter: 1000

rabbit:
  address: 127.0.0.1
  username: admin
  password: admin
  virtual-host: \

log_path: .
debug_mode: True

learning:
  learning-rate: 0.01
  momentum: 0.5
  batch-size: 32
  control-count: 3
