name: Split Learning
server:
  global-round : 1
  t-g: 4 # global
  t-c: 2 # client
  clients:
    - 9
    - 3
  num-cluster: 3
  cut-layer: # VGG16[4,7] , Bert [2,3]
    - 7
    - 7
    - 4
  select-ratio: 0.5
  model: VGG16
  data-name: CIFAR10
  data-distribution:
    non-iid: True
    num-sample: 5000
    num-label: 10

rabbit:
  address: 127.0.0.1
  username: admin
  password: admin
  virtual-host: /

log_path: .
debug_mode: True

learning:
  learning-rate: 0.00001
  momentum: 0.5
  batch-size: 32
  weight-decay: 0.01